#### 配置项目启动端口号
server:
  port: 9999
spring:
  ###### 配置项目应用名
  application:
    name: car-server
###### 配置Eureka Server
eureka:
  ##### 设定Eureka server 的 host信息
  instance:
    hostname: localhost
  client:
    ##### 禁止注册中心将自身服务进行系统注册
    register-with-eureka: false
    ##### 禁止本注册中心去其他注册中心发现服务
    fetch-registry: false
    ##### 设定Client 链接注册中心暴露地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
